name: "Day 4: Speed Up CI with Caching"
on:
  push:
    branches:
      - day4
  pull_request:
    branches:
      - day4
defaults:
  run:
    working-directory: ./day-4
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.4
          cache: false
      - name: Cache Go modules and build
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-build-cache-go-${{ hashFiles('day-4/go.mod') }}
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: go test -v ./...